# -*- coding: utf-8 -*-
"""LVADSUSR78_lokesh_BPA_IA-2_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GWcLbnE9-NvAJZyRPXG42DKS1pqR3a-i
"""

#1
import pandas as pd
data=pd.read_csv("/content/sample_data/winequality-red.csv")
df=pd.DataFrame(data)
df.head()

#finding null values

df.isnull().sum()

#to fill the null values we use
df = df.fillna(method='ffill')
#here we use forwordfill method to fill the all NaN value

#removing outliers from the data set
import matplotlib.pyplot as plt
plt.boxplot(df['fixed acidity'])
plt.show()

#here we have outliers

df=df[df['fixed acidity']<12]


plt.boxplot(df['free sulfur dioxide'])
plt.show()

df=df[df['free sulfur dioxide']<40]


plt.boxplot(df['total sulfur dioxide'])
plt.show()

df=df[df['total sulfur dioxide']<=104]

l=[]
for i in df['quality']:
  if i<=6:
    l.append(0)
  elif i>6 and i<=8:
    l.append(1)
print(l)

df['Target_Quality']=l

#here we are Droping duplicate rows from the dataset
df.drop_duplicates(inplace=True)

X=df.drop(['Target_Quality','quality'],axis=1)
y=df['Target_Quality']

from sklearn.model_selection import train_test_split


X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)



from sklearn.neighbors import KNeighborsClassifier
KNC_classifier = KNeighborsClassifier()
print("KNeighborsClassifier")

## Model Training
KNC_classifier.fit(X_train,y_train)

## Model Testing
KNC_predictions=KNC_classifier.predict(X_test)


from sklearn.metrics import accuracy_score, precision_score, recall_score

KNC_model_accuracy = accuracy_score(KNC_predictions,y_test)
print("Precision :", precision_score(KNC_predictions,y_test))
print("recall :", recall_score(KNC_predictions,y_test))
print("Accuracy :", KNC_model_accuracy)