# -*- coding: utf-8 -*-
"""LVADSUSR78_lokesh_BPA_IA-2_Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M_H08ZiZexBkKaPaR0pXyt-T04FrBpPm
"""

import pandas as pd

data = pd.read_csv("/content/sample_data/Mall_Customers.csv")
data.head()

data.info()

data.describe()

# Imputing missing values

data = data.fillna(method="ffill")
data.isnull().sum()
data.head()

# normalizing features data
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt

scaler = MinMaxScaler()
data['Annual Income (k$)'] = scaler.fit_transform(data[['Annual Income (k$)']])
data.head()

data['Spending Score (1-100)'] = scaler.fit_transform(data[['Spending Score (1-100)']])
data.head()

plt.scatter(data['Age'], data['Spending Score (1-100)'], color = 'green')
plt.title("Relation between age and spending score")
plt.xlabel('Age')
plt.ylabel('Spending score')
plt.show()

# Encoding categorical data
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
data['Gender'] = encoder.fit_transform(data[['Gender']])
data.head()

# Elbow method to find no of clusters

sse = []
k_rng = range(1,10)
for k in k_rng:
    km = KMeans(n_clusters=k)
    km.fit(data[['Age','Spending Score (1-100)']])
    sse.append(km.inertia_)
plt.plot(k_rng, sse)
plt.xlabel("clusters")
plt.title("Elbow method to find no of clusters")
plt.show()

# model bulding
from sklearn.cluster import KMeans


model = KMeans(n_clusters = 4)
pred = model.fit_predict(data[['Age', 'Spending Score (1-100)']])

data['cluster'] = pred
df1 = data[data.cluster==0]
df2 = data[data.cluster==1]
df3 = data[data.cluster==2]
df4 = data[data.cluster==3]

plt.scatter(df1.Age,df1['Spending Score (1-100)'],color='green')
plt.scatter(df2.Age,df2['Spending Score (1-100)'],color='red')
plt.scatter(df3.Age,df3['Spending Score (1-100)'],color='black')
plt.scatter(df4.Age,df4['Spending Score (1-100)'],color='blue')
plt.scatter(model.cluster_centers_[:,0],model.cluster_centers_[:,1],color='purple',marker='*',label='centroid')
plt.xlabel('AgeGroup')
plt.ylabel('Spend')
plt.legend()

# first two segments(green + black)
# the First two clusters with green and Black color are spending more amount to us,
# so they are classified as high spending customers and they are very young aged people fall between 18-40.


# last two segments(blue + red)
# the next two clusters with blue and red color are spending less compared to other customer segments,
# they are 45-70 aged people, so we can say that aged people spending less than the younger people.

# male + younger(18-40) customer are more likely to spend more than the others

# female + younger (18-40) customer are spending average amount of money compared to others

# male or female + older(40-70) customer are spending less compared to others ,
#even they are earning better than the others.

# Target the younger people by introducing more prodcuts on which they are spending,
# to produce more profits , as they are clearly spending more money
# than others irrespective of how much they are earning

# last two segments are aged people, invent some more marketing strategies to attract these aged people