# -*- coding: utf-8 -*-
"""Python_Internal_Assesment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nbikIGXJpgH5omTFfoYBz_FU44i1j1PP
"""

from google.colab import drive
drive.mount("/content/drive")

#1
length = int(input("Enter length of rectangle :"))
width = int(input("Enter width of rectangle :"))
print("Area of Rectangle : ", (length * width))

#2
weight = int(input("Enter Weight (Kgs) :"))
height = int(input("Enter Height (Meter) :"))
print("Body Mass Index (BMI) : ", (weight/(height**2)))

#3
student_dictionary = dict()
t = int(input("No of students you want to add: "))
for i in range(t):
  name = input("Student name :")
  score = int(input("Score of student :"))
  student_dictionary[name]=score

print("Studsent Dictionary :a", student_dictionary)

#4
age = int(input())
if(age<18):
  print("Minor")
elif(age>=18 and age <60):
  print("Adult")
elif(age>=60):
  print("Senior")

#5
for i in range(2,50, 2):
  print(i)

#6
password='1234'
entered_password = input("Enter Password :")
while(entered_password!=password):
  entered_password = input("Password Incorrect! Enter again :")
print("Password Entered correctly")

#7

def avg_of_list(list1):
  return sum(list1)/len(list1)

entered_list=[]
t=int(input("Enter no of elements want to insert into list : "))
for i in range(t):
  entered_list.append( int(input("Enter Element :")))

print("Average of given list of values : ",avg_of_list(entered_list))

#8

def count_vowels(str):
  count=0
  for i in str:
    if i in 'a,e,i,o,u,A,E,I,O,U':
      count+=1
  return count
string1 = input()
print("count of vowels in given string : ", count_vowels(string1))

#9
from datetime import datetime
print(datetime.now())

#10
def addition():
  try:
    value1 = 12
    value2 = 'abc'
    print(value1+value2)
  except ValueError:
    print("Value Erro: Values cannot be added")
  except Exception as e:
    print("Value Error , Values cannot be added")
addition()

#11
def error_handle():
  try:
    int_value = int(input())
    print("integer value entered successfully")
  except ValueError:
    print("Value Error: Expecting an int value")
  except Exception as e:
    print(e)
error_handle()

#12
def division(num1, num2):
  try :
    print(num1/num2)
  except ZeroDivisionError:
    print("Cannot Divide a value with zero")
  except Exception as e:
    print(e)

num1 = int(input("Enter Numerator : "))
num2 = int(input("Enter Denominator : "))
division(num1, num2)

#13
try :
  with open('/content/drive/MyDrive/sample.txt', "w")as file:
    file.write("Hello Python!")
except FileNotFoundError:
  print("file not found")
except Exception as e:
  print(e)

#14
try :
  with open('/content/drive/MyDrive/sample.txt', "r")as file:
    data = file.read()
    print("contents in file :")
    print(data)
except FileNotFoundError:
  print("File not found")
except Exception as e:
  print(e)

#15
try :

  with open('/content/drive/MyDrive/sample.txt', "a") as file:
    file.write("Appending a new Line ")
  with open('/content/drive/MyDrive/sample.txt', "r")as file:
    data = file.read()
    print(data)
except FileNotFoundError:
  print("File not found")
except Exception as e:
  print(e)